const ADD_ITEM = 'ADD_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const EDIT_ITEM = 'EDIT_ITEM';
const CHANGE_NAME = 'CHANGE_NAME';
const CHANGE_PRICE = 'CHANGE_PRICE';
const EDIT_ID = 'EDIT_ID';
const DELETE_MISMATCHED_VALUES = 'DELETE_MISMATCHED_VALUES';

export const actionTypes = {ADD_ITEM, DELETE_ITEM, EDIT_ITEM, CHANGE_NAME, CHANGE_PRICE, EDIT_ID, DELETE_MISMATCHED_VALUES};
